### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by MelissaMV** [NullArray/DorkNet#3]
I have the latest installation of Selenium 3.8.1, Geckodriver 0.19.1 and Firefox 57.0.4 (32-bit) but I'm getting this error:

[+]Would you like DorkNet to proxy it's connection to the search engine?
[Y]es/[N]o: Y 

[!]Unhandled option, defaulting to unproxied connection...
Traceback (most recent call last):
  File "dorknet.py", line 154, in <module>
    proc_one = search()
  File "dorknet.py", line 107, in search
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

root@kali:~/Desktop/DorkNet#

How can i solve this plz??

**Comment by NullArray** [comment]
Hey @MelissaMV i've looked around and it seems people were experiencing the same issue with the chromedriver. It was suggested on stackoverflow to fully uninstall all versions of your driver, which in this case would be the Geckodriver. Make sure to delete all related files as well. Try to run this command to locate the files in question.

`sudo find /* -name "geckodriver` 

After that do fresh install of the latest geckodriver. If that doesn't work get back to me.

**Comment by MelissaMV** [comment]
Hey @NullArray thx for your reply :) ok i did fresh install of geckodriver and got the following error:

Traceback (most recent call last):
  File "dorknet.py", line 58, in <module>
    print "[" + t.magenta("~") + "]" + line 
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 6: ordinal not in range(128)

Do I need to proxy my connection for it to work?

**Comment by NullArray** [comment]
I take it `my_dorks` is a textfile? For one i don't think it's necessary to surround the path to your list in single quotes. this is because the `raw_input` syntax treats the input as a string anyway.

An `UniCodeDecodeError` would seem to suggest the interpreter can't parse whatever it is trying to print that is contained within the `line` variable. How is your dork list formatted?

A proper formatted list would look a little like this:
```
about.php?cartID=
accinfo.php?cartId=
acclogin.php?cartID=
add.php?bookid=
```
Would you mind pasting a snippet of the dorks that you have in your dork list? Also, it is not necessary to proxy the connection of the program in order for it to function properly.

**Comment by NullArray** [comment]
Oh and, capital Y is unhandled since i assume everyone uses non-capital letters. But i'll fix that right quick.

https://github.com/NullArray/DorkNet/commit/5b8bf2f0389483267d331f77331ae8007a7a36d4

There we go.

**Comment by MelissaMV** [comment]
Hi @NullArray sure these are some of the dorks in my_dorks list and no it wasn't in .txt format it's in the format i downloaded it from GHDB - when i downloaded it i didn't include .txt in the command line but just my_dorks.

I will try it in .txt format and remove the quotes and get back to you :)

intitle:"Apache Tomcat" "Error Report"
ext:asp "[ODBC SQL"
intext:"ADODB.Field" OR intext:"ADODB.Command"
intext:"Input string was not in a correct format"
intext: inurl:"*.php?*=*.php" intext:"Warning: include" -inurl:.html
intext:"Warning:" "failed to open stream: HTTP request failed" "on line"
intext:"Fatal error: Class \'Red_Action\' not found in"
intext:"[function.getimagesize]: failed to open stream: No such file or directory in"
intext: "Warning: Cannot modify header information - headers already sent"
intext:"Syntax error" OR intext:"GetArray()" OR intext:"FetchRow()"
intitle:"Index of" OR "Index of /backup" ',
intitle:"Index of" .mysql_history OR intitle:index.of ws_ftp.ini OR intitle:index.of .bash_history
inurl:admin OR inurl:administrator OR intitle:admin +intitle:login
intitle:"401 Authorization required" ',
inurl:admin.php OR inurl:administrator.php OR inurl:cms.php
inurl:"smb.conf" intext:"workgroup" ext:conf
inurl:server-status intext:"Apache"
intitle:phpinfo "PHP Version"

**Comment by NullArray** [comment]
Sure thing, let me know how it goes.

**Comment by MelissaMV** [comment]
hola @NullArray I think I did everything by the book lol but i'm still getting the following error. I think it might be my Kali Linux that has some screwed up configurations. Anywayz thank you for trying to help me :)

[+]Would you like DorkNet to proxy it's connection to the search engine?
[Y]es/[N]o: no

[!]Unhandled option, defaulting to unproxied connection...
Traceback (most recent call last):
  File "dorknet.py", line 154, in <module>
    proc_one = search()
  File "dorknet.py", line 107, in search
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

root@kali:~/Desktop/DorkNet#

**Comment by NullArray** [comment]
Your dorks are being loaded properly so that's good. Also, you answer the prompt with a simply `y` or `n`. Full "Yes" or "No" is unhandled. In any case, looks like the issue is with your selenium library or Geckodriver version.

If you could open up a terminal and paste this command;
`python -c "import selenium; print(selenium.__version__)`
And post your result that'd be great.

For reference, my Selenium version is `3.7.0` on Python `2.7.12`.
