### ISSUE TITLE
save result to file

### ISSUE THREAD

**Issue by sadazs** [NullArray/DorkNet#6]
Hi! when use Dorknet it not save result to file and return to google search with search detail
how to save result to file
Thank!

**Comment by NullArray** [comment]
Hi, sorry for the late reply. I've been a bit busy as of late. First of all, do you have write permission in the directory you are running DorkNet from? Also, are there any error messages that pop up at all during the execution of the program?

**Comment by NullArray** [comment]
Anyway since it's been a while i'll assume you got this issue fixed. If not please feel free to open a ticket again.
